-- Structure de la base de reservation de salles.
-- Les noms, codes et e-mails uniques utilisent la collation NOCASE : l'unicite
-- est donc verifiee sans tenir compte de la casse, comme le demande le contrat.

CREATE TABLE BUILDING
(
    ID               INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME             VARCHAR(100) NOT NULL COLLATE NOCASE UNIQUE,
    NUMBER_OF_FLOORS INTEGER      NOT NULL CHECK (NUMBER_OF_FLOORS BETWEEN 1 AND 200)
);

CREATE TABLE EQUIPMENT
(
    ID    INTEGER PRIMARY KEY AUTOINCREMENT,
    CODE  VARCHAR(50)  NOT NULL COLLATE NOCASE UNIQUE,
    LABEL VARCHAR(100) NOT NULL
);

CREATE TABLE ROOM
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME        VARCHAR(100) NOT NULL COLLATE NOCASE UNIQUE,
    BUILDING_ID INTEGER      NOT NULL,
    FLOOR       INTEGER      NOT NULL CHECK (FLOOR >= 0),
    CAPACITY    INTEGER      NOT NULL CHECK (CAPACITY > 0),
    STATUS      VARCHAR(20)  NOT NULL CHECK (STATUS IN ('AVAILABLE', 'MAINTENANCE')),

    FOREIGN KEY (BUILDING_ID) REFERENCES BUILDING (ID)
);

CREATE TABLE ROOM_EQUIPMENT
(
    ROOM_ID      INTEGER NOT NULL,
    EQUIPMENT_ID INTEGER NOT NULL,

    PRIMARY KEY (ROOM_ID, EQUIPMENT_ID),
    FOREIGN KEY (ROOM_ID) REFERENCES ROOM (ID) ON DELETE CASCADE,
    FOREIGN KEY (EQUIPMENT_ID) REFERENCES EQUIPMENT (ID) ON DELETE CASCADE
);

CREATE TABLE ORGANIZER
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME        VARCHAR(150) NOT NULL,
    EMAIL       VARCHAR(254) NOT NULL COLLATE NOCASE UNIQUE,
    BUILDING_ID INTEGER      NOT NULL,
    FLOOR       INTEGER      NOT NULL CHECK (FLOOR >= 0),

    FOREIGN KEY (BUILDING_ID) REFERENCES BUILDING (ID)
);

CREATE TABLE RESERVATION
(
    ID                     INTEGER PRIMARY KEY AUTOINCREMENT,
    TITLE                  VARCHAR(200) NOT NULL,
    ROOM_ID                INTEGER      NOT NULL,
    ORGANIZER_ID           INTEGER      NOT NULL,
    START_AT               TIMESTAMP    NOT NULL,
    END_AT                 TIMESTAMP    NOT NULL,
    NUMBER_OF_PARTICIPANTS INTEGER      NOT NULL CHECK (NUMBER_OF_PARTICIPANTS > 0),
    STATUS                 VARCHAR(20)  NOT NULL CHECK (STATUS IN ('CONFIRMED', 'CANCELLED')),
    CREATED_AT             TIMESTAMP    NOT NULL,

    FOREIGN KEY (ROOM_ID) REFERENCES ROOM (ID),
    FOREIGN KEY (ORGANIZER_ID) REFERENCES ORGANIZER (ID)
);

-- Les equipements exiges sont conserves tels qu'ils ont ete demandes, meme si la
-- salle perd un equipement par la suite : la reservation reste consultable a l'identique.
CREATE TABLE RESERVATION_EQUIPMENT
(
    RESERVATION_ID INTEGER     NOT NULL,
    EQUIPMENT_CODE VARCHAR(50) NOT NULL,

    PRIMARY KEY (RESERVATION_ID, EQUIPMENT_CODE),
    FOREIGN KEY (RESERVATION_ID) REFERENCES RESERVATION (ID) ON DELETE CASCADE
);

-- Index utilises par la recherche de disponibilite et le filtrage des reservations.
CREATE INDEX IDX_RESERVATION_ROOM_PERIOD ON RESERVATION (ROOM_ID, STATUS, START_AT, END_AT);
CREATE INDEX IDX_ROOM_BUILDING ON ROOM (BUILDING_ID);

INSERT INTO BUILDING (ID, NAME, NUMBER_OF_FLOORS)
VALUES (1, 'Batiment A', 5),
       (2, 'Batiment B', 3);

INSERT INTO EQUIPMENT (ID, CODE, LABEL)
VALUES (1, 'PROJECTOR', 'Videoprojecteur'),
       (2, 'WHITEBOARD', 'Tableau blanc'),
       (3, 'VIDEO_CONFERENCE', 'Systeme de visioconference');

INSERT INTO ROOM (ID, NAME, BUILDING_ID, FLOOR, CAPACITY, STATUS)
VALUES (1, 'Orion', 1, 2, 30, 'AVAILABLE'),
       (2, 'Cassiopee', 1, 3, 12, 'AVAILABLE'),
       (3, 'Pegase', 2, 0, 50, 'AVAILABLE');

INSERT INTO ROOM_EQUIPMENT (ROOM_ID, EQUIPMENT_ID)
VALUES (1, 1),
       (1, 2),
       (2, 2),
       (3, 1),
       (3, 2),
       (3, 3);

INSERT INTO ORGANIZER (ID, NAME, EMAIL, BUILDING_ID, FLOOR)
VALUES (1, 'Alice Martin', 'alice.martin@example.org', 1, 2),
       (2, 'Bob Durand', 'bob.durand@example.org', 2, 1);
